import { addSample, createSession, getVerticalDirection, resultState } from './wheelAnalyzer';
import { drawSignal } from './wheelCanvas';
import { track } from '../../utils/analytics';
import type { WheelTestSession } from './types';

const root = document.querySelector<HTMLElement>('[data-scroll-tester]');
if (root) {
  const area = root.querySelector<HTMLElement>('[data-wheel-area]')!; const canvas = root.querySelector<HTMLCanvasElement>('canvas')!;
  const resetButton = root.querySelector<HTMLButtonElement>('[data-reset]')!;
  let session: WheelTestSession | null = null; let frame = 0;
  const setText = (key: string, value: string) => { const el = root.querySelector<HTMLElement>(`[data-${key}]`); if (el) el.textContent = value; };
  const render = () => { frame = 0; drawSignal(canvas, session?.samples || []); if (!session) return; setText('total', String(session.totalEvents)); setText('expected', String(session.expectedEvents)); setText('reverse', String(session.reverseEvents)); setText('rate', `${session.reverseRate.toFixed(2)}%`); setText('gap', `${Math.round(session.longestGap)} ms`); setText('event-rate', `${(session.totalEvents / Math.max(1, (performance.now() - session.startedAt) / 1000)).toFixed(1)} events/sec`); const state = resultState(session); const result = root.querySelector<HTMLElement>('[data-result]')!; if (state === 'collecting') { result.className = 'result-note collecting'; result.innerHTML = '<strong>Keep scrolling…</strong><span>Collect at least 20 events for a more useful result.</span>'; } else if (state === 'reverse') { result.className = 'result-note warning'; result.innerHTML = `<strong>Possible reverse scrolling detected</strong><span>${session.reverseEvents} events moved in the opposite direction. Repeat the test 2–3 times before drawing a conclusion.</span>`; } else { result.className = 'result-note success'; result.innerHTML = '<strong>No obvious reverse scrolling detected</strong><span>All recorded events matched your selected scroll direction during this test.</span>'; } };
  const queue = () => { if (!frame) frame = requestAnimationFrame(render); };
  const start = (direction: 'up' | 'down') => { session = createSession(direction); root.dataset.active = 'true'; setText('chosen-direction', direction === 'down' ? 'Scrolling down' : 'Scrolling up'); area.focus(); drawSignal(canvas, []); root.querySelector<HTMLElement>('[data-result]')!.innerHTML = '<strong>Live test ready</strong><span>Keep scrolling steadily in the same direction.</span>'; track('scroll_test_started', { direction }); };
  area.addEventListener('wheel', (event) => { event.preventDefault(); if (!session) { const direction = getVerticalDirection(event.deltaY); if (direction !== 'up' && direction !== 'down') return; start(direction); } if (!session) return; session = addSample(session, { timestamp: performance.now(), deltaX: event.deltaX, deltaY: event.deltaY, deltaMode: event.deltaMode, inputType: 'unknown' }); queue(); if (session.totalEvents === 20) track('scroll_test_completed', { direction: session.expectedDirection, sample_bucket: '20-99', reverse_detected: session.reverseEvents > 0 }); }, { passive: false });
  resetButton.addEventListener('click', () => { session = null; root.dataset.active = 'false'; setText('chosen-direction', 'Scroll to begin'); ['total', 'expected', 'reverse'].forEach((key) => setText(key, '0')); setText('rate', '0.00%'); setText('gap', '0 ms'); setText('event-rate', '0 events/sec'); root.querySelector<HTMLElement>('[data-result]')!.className = 'result-note collecting'; root.querySelector<HTMLElement>('[data-result]')!.innerHTML = '<strong>Ready when you are</strong><span>Scroll inside the test area to begin.</span>'; drawSignal(canvas, []); track('scroll_test_reset'); });
  new ResizeObserver(() => drawSignal(canvas, session?.samples || [])).observe(canvas); drawSignal(canvas, []);
}
